default:
    trainer: ppo
    batch_size: 64
    beta: 0.001
    buffer_size: 12000
    epsilon: 0.2
    gamma: 0.995
    hidden_units: 128
    lambd: 0.99
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 2
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: true
    curiosity_strength: 0.01
    curiosity_enc_size: 128

